# Generated by Django 4.1.13 on 2025-03-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_album_image_url_alter_album_release_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
