# Generated by Django 4.1.13 on 2025-03-20 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_album_release_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='image_url',
            field=models.URLField(blank=True),
        ),
    ]
