# Generated by Django 4.1.13 on 2025-03-21 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LovedSongs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loved_by', to='api.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loved_songs', to='api.user')),
            ],
            options={
                'db_table': 'loved_songs',
                'unique_together': {('user', 'songs')},
            },
        ),
    ]
