# Generated by Django 5.1.7 on 2026-10-05 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_user_ispremium'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='cover_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
